# Generated by Django 2.0 on 2018-05-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_followed', to='users.Profile')),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_foolowing', to='users.Profile')),
            ],
        ),
    ]
