# Generated by Django 2.0 on 2018-05-13 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.CharField(default=None, max_length=64)),
                ('like', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
